# Generated by Django 5.2.3 on 2025-06-14 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='在庫数')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='本')),
            ],
            options={
                'verbose_name': '本の在庫',
                'verbose_name_plural': '本の在庫',
                'db_table': 'book_stock',
            },
        ),
    ]
